DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS read;
DROP TABLE IF EXISTS tagList;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	author_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	body BLOB NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE tags (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	post_id INTEGER NOT NULL,
	tagid INTEGER NOT NULL,
	FOREIGN KEY (post_id) REFERENCES post (id),
	FOREIGN KEY (tagid) REFERENCES tagList (id)
);

CREATE TABLE read (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	userid INTEGER NOT NULL,
	readcount INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (userid) REFERENCES user (id)
);

CREATE TABLE tagList (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	tagname TEXT NOT NULL UNIQUE
);
